function t229_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t229__list_item a[href=\''+url+'\'], '+'.t229__list_item a[href=\''+url+'/\'], '+'.t229__list_item a[href=\''+pathname+'\'], '+'.t229__list_item a[href=\'/'+pathname+'\'], '+'.t229__list_item a[href=\''+pathname+'/\'], '+'.t229__list_item a[href=\'/'+pathname+'/\']');Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t229_checkAnchorLinks(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<980)return;var navLinks=rec.querySelectorAll('.t229__list_item a[href*=\'#\']');navLinks=Array.prototype.filter.call(navLinks,function(navLink){return!navLink.classList.contains('tooltipstered')});if(navLinks.length){t229_catchScroll(navLinks)}}
function t229_catchScroll(navLinks){navLinks=Array.prototype.slice.call(navLinks);var clickedSectionID=null;var sections=[];var sectionToNavigationLinkID={};var interval=100;var lastCall;var timeoutID;if(Array.isArray(navLinks)){navLinks=navLinks.reverse()}
Array.prototype.forEach.call(navLinks,function(link){var currentSection=t229_getSectionByHref(link);if(currentSection&&currentSection.id){sections.push(currentSection);sectionToNavigationLinkID[currentSection.id]=link}});t229_updateSectionsOffsets(sections);sections.sort(function(a,b){var firstTopOffset=parseInt(a.getAttribute('data-offset-top'),10)||0;var secondTopOffset=parseInt(b.getAttribute('data-offset-top'),10)||0;return secondTopOffset-firstTopOffset});window.addEventListener('resize',t_throttle(function(){t229_updateSectionsOffsets(sections)},200));if(typeof jQuery!=='undefined'){$('.t229').bind('displayChanged',function(){t229_updateSectionsOffsets(sections)})}else{var menuEls=document.querySelectorAll('.t229');Array.prototype.forEach.call(menuEls,function(menu){menu.addEventListener('displayChanged',function(){t229_updateSectionsOffsets(sections)})})}
setInterval(function(){t229_updateSectionsOffsets(sections)},5000);t229_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID);Array.prototype.forEach.call(navLinks,function(navLink,i){navLink.addEventListener('click',function(){var clickedSection=t229_getSectionByHref(navLink);if(!navLink.classList.contains('tooltipstered')&&clickedSection&&clickedSection.id){navLinks.forEach(function(link,index){if(index===i){link.classList.add('t-active')}else{link.classList.remove('t-active')}});clickedSectionID=clickedSection.id}})});window.addEventListener('scroll',function(){var dateNow=new Date().getTime();if(lastCall&&dateNow<lastCall+interval){clearTimeout(timeoutID);timeoutID=setTimeout(function(){lastCall=dateNow;clickedSectionID=t229_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)},interval-(dateNow-lastCall))}else{lastCall=dateNow;clickedSectionID=t229_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)}})}
function t229_updateSectionsOffsets(sections){sections.forEach(function(section){var sectionTopPos=section.getBoundingClientRect().top+window.pageYOffset;section.setAttribute('data-offset-top',sectionTopPos)})}
function t229_getSectionByHref(curlink){if(!curlink)return;var href=curlink.getAttribute('href');var curLinkValue=href?href.replace(/\s+/g,''):'';if(curLinkValue.indexOf('/')===0)curLinkValue=curLinkValue.slice(1);if(href&&curlink.matches('[href*="#rec"]')){curLinkValue=curLinkValue.replace(/.*#/,'');return document.getElementById(curLinkValue)}else{var selector=href?href.trim():'';var slashIndex=selector.indexOf('#')!==-1?selector.indexOf('#'):!1;if(typeof slashIndex==='number'){selector=selector.slice(slashIndex+1)}else{slashIndex=selector.indexOf('/')!==-1?selector.indexOf('/'):!1;if(typeof slashIndex==='number')selector=selector.slice(slashIndex+1)}
var fullSelector='.r[data-record-type="215"] a[name="'+selector+'"]';return document.querySelector(fullSelector)?document.querySelector(fullSelector).closest('.r'):null}}
function t229_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID){var scrollPosition=window.pageYOffset;var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var returnValue=clickedSectionID;var lastSection=sections.length?sections[sections.length-1]:null;var lastSectionTopPos=lastSection?lastSection.getAttribute('data-offset-top'):'0';lastSectionTopPos=parseInt(lastSectionTopPos,10)||0;if(sections.length&&clickedSectionID===null&&lastSectionTopPos>(scrollPosition+300)){navLinks.forEach(function(link){link.classList.remove('t-active')});return null}
for(var i=0;i<sections.length;i++){var sectionTopPos=sections[i].getAttribute('data-offset-top');var navLink=sections[i].id?sectionToNavigationLinkID[sections[i].id]:null;if(scrollPosition+300>=sectionTopPos||i===0&&scrollPosition>=scrollHeight-window.innerHeight){if(clickedSectionID===null&&navLink&&!navLink.classList.contains('t-active')){navLinks.forEach(function(link){link.classList.remove('t-active')});if(navLink)navLink.classList.add('t-active');returnValue=null}else if(clickedSectionID!==null&&sections[i].id&&clickedSectionID===sections[i].id){returnValue=null}
break}}
return returnValue}
function t229_setBg(recid){var menuBlocks=document.querySelectorAll('.t229');Array.prototype.forEach.call(menuBlocks,function(menu){if(window.innerWidth>980){if(menu.getAttribute('data-bgcolor-setbyscript')==='yes'){menu.style.backgroundColor=menu.getAttribute('data-bgcolor-rgba')}}else{menu.style.backgroundColor=menu.getAttribute('data-bgcolor-hex');menu.setAttribute('data-bgcolor-setbyscript','yes');if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''}})}
function t229_appearMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<=980)return;var menuBlocks=rec.querySelectorAll('.t229');Array.prototype.forEach.call(menuBlocks,function(menu){var appearOffset=menu.getAttribute('data-appearoffset');if(appearOffset){if(appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(typeof appearOffset==='number'&&window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t229_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t229_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t229_slideUpElement(menu,menuHeight,position){var diff=position==='toTop'?0:menuHeight;var diffOpacity=position==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=position==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=position==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(position==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(position==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t229_changeBgOpacityMenu(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t229');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity-two');var menuShadow=menu.getAttribute('data-menushadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t270_scroll(hash,offset,speed){if(!speed)speed=400;if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var target;if(!hash)return;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return!0}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"]');if(!target)return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;target=parseInt(target.getBoundingClientRect().top+window.pageYOffset-offset,10);if(window.isIE){window.scrollTo(0,target)}else{window.scrollTo({left:0,top:target,behavior:'smooth',})}
if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t300_init(){var tooltipBlocks=document.querySelectorAll('.t300');Array.prototype.forEach.call(tooltipBlocks,function(tooltip){var hook=tooltip.getAttribute('data-tooltip-hook');var tooltipId=tooltip.getAttribute('data-tooltip-id');if(hook!==''){if(typeof window.tooltipster!=='undefined'){var links=document.querySelectorAll('a[href="'+hook+'"]:not(.tooltipstered)')}else{var links=$('a[href="'+hook+'"]:not(.tooltipstered)')}
var content=tooltip.querySelector('.t300__content').innerHTML;var touchDevices=!1;if(hook.charAt(0)=='#'){touchDevices=!0}
var position=tooltip.getAttribute('data-tooltip-position');if(position===''){position='top'}
if(typeof window.tooltipster!=='undefined'){window.tooltipster(links,{theme:'t300__tooltipster-noir t300__tooltipster-noir_'+tooltipId+'',contentAsHTML:!0,content:content,interactive:!0,touchDevices:touchDevices,position:position})}else{links.tooltipster({theme:'t300__tooltipster-noir t300__tooltipster-noir_'+tooltipId+'',contentAsHTML:!0,content:content,interactive:!0,touchDevices:touchDevices,position:position})}}})}
document.addEventListener('DOMContentLoaded',function(){t_onFuncLoad('tooltipster',function(){t300_init();setTimeout(function(){var stores=document.querySelector('body .t-store');if(stores){Array.prototype.forEach.call(stores,function(store){new MutationObserver(function(mutationsList){for(var mutation in mutationsList){var event=mutationsList[mutation];if(event.type==='attributes'){if(event.target.className.indexOf('t-popup_show')!=-1){t300_init()}}}}).observe(store,{attributes:!0,attributeFilter:['class'],subtree:!0})})}
t300_init()},500)})});function t390_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var escapeEvent=t390_escClosePopup.bind(this,recId);if(popupTooltipHook){var recBlocks=document.querySelectorAll('.r');for(var i=0;i<recBlocks.length;i++){recBlocks[i].addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t390_showPopup(recId,escapeEvent);t390_resizePopup(recId);t390__lazyLoad();if(analitics){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}})}}
popup.addEventListener('scroll',t_throttle(function(){t390__lazyLoad()}));popup.addEventListener('click',function(event){if(event.target===this)t390_closePopup(recId,escapeEvent)});popupCloseBtn.addEventListener('click',function(){t390_closePopup(recId,escapeEvent)});for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t390_closePopup(recId,escapeEvent);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){document.body.classList.add('t-body_popupshowed')},300)}}})}
var curPath=window.location.pathname;var curFullPath=window.location.origin+curPath;var isAndroid=/(android)/i.test(navigator.userAgent);if(isAndroid){var selects='a[href^="#"]:not([href="#"]):not([href^="#price"]):not([href^="#popup"]):not([href^="#prodpopup"]):not([href^="#order"]):not([href^="#!"]),'+'a[href^="'+curPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"]),'+'a[href^="'+curFullPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"])';var selectors=rec.querySelectorAll(selects);for(var i=0;i<selectors.length;i++){selectors[i].addEventListener('click',function(event){var hash=this.hash.trim();if(window.location.hash){setTimeout(function(){window.location.href=hash},50)}})}}
function t390_escClosePopup(recId){if(arguments[1].key==='Escape')t390_closePopup(recId,escapeEvent)}}
function t390_showPopup(recId,escapeEvent){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var documentBody=document.body;popup.style.display='block';setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},50);documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t390__body_popupshowed');document.addEventListener('keydown',escapeEvent)}
function t390_closePopup(recId,escapeEvent){var rec=document.getElementById('rec'+recId);var popup=rec.querySelector('.t-popup');var popupActive=document.querySelector('.t-popup.t-popup_show');if(popup===popupActive){document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t390__body_popupshowed')}
popup.classList.remove('t-popup_show');setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',escapeEvent)}
function t390_resizePopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var popupContainer=rec.querySelector('.t-popup__container');if(!popupContainer)return;var popupStyle=getComputedStyle(popupContainer,null);var popupPaddingTop=parseInt(popupStyle.paddingTop)||0;var popupPaddingBottom=parseInt(popupStyle.paddingBottom)||0;var popupHeight=popupContainer.clientHeight-(popupPaddingTop+popupPaddingBottom);if(popupHeight>(window.innerHeight-120)){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t390_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t390__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t395_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var allRecords=document.getElementById('allrecords');var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var tildaLazyMode=allRecords?allRecords.getAttribute('data-tilda-lazy'):'';var tabs=rec?rec.querySelectorAll('.t395__tab'):[];if(tildaMode!=='edit'&&tildaMode!=='preview'){t395_scrollToTabs(recid)}
Array.prototype.forEach.call(tabs,function(tab,i){tab.addEventListener('click',function(e){var targetTab=e.target.closest('.t395__tab');if(targetTab&&targetTab.classList.contains('t395__tab_active')&&!e.isTrusted)return;var activeTab=rec.querySelector('.t395__tab_active');if(activeTab)activeTab.classList.remove('t395__tab_active');targetTab.classList.add('t395__tab_active');t395_removeUrl();var tabNumber=i+1;if(tildaMode!=='edit'&&tildaMode!=='preview'&&tabNumber&&typeof history.replaceState!=='undefined'){try{window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumber)}catch(err){}}
t395_alltabs_updateContent(recid);t395_updateSelect(recid);var hookBlocks=targetTab.getAttribute('data-tab-rec-ids').split(',');var event=document.createEvent('Event');event.initEvent('displayChanged',!0,!0);hookBlocks.forEach(function(curRecid){var currentRec=document.getElementById('rec'+curRecid);if(!currentRec)return;var currentRecChildren=currentRec.querySelectorAll('.t-feed, .t-store, .t-store__product-snippet, .t117, .t121, .t132, .t223, .t226, .t228, .t229, .t230, .t268, .t279, .t341, .t346, .t347, .t349, .t351, .t353, .t384, .t385, .t386, .t396, .t400, .t404, .t409, .t410, .t412, .t418, .t422, .t425, .t428, .t433, .t448, .t456, .t477, .t478, .t480, .t486, .t498, .t504, .t506, .t509, .t511, .t517, .t518, .t519, .t520, .t532, .t533, .t538, .t539, .t544, .t545, .t552, .t554, .t569, .t570, .t577, .t592, .t598, .t599, .t601, .t604, .t605, .t609, .t615, .t616, .t650, .t659, .t670, .t675, .t686, .t688, .t694, .t698, .t700, .t726, .t728, .t730, .t734, .t738, .t740, .t744, .t754, .t760, .t762, .t764, .t774, .t776, .t778, .t780, .t786, .t798, .t799, .t801, .t813, .t814, .t822, .t826, .t827, .t829, .t842, .t843, .t849, .t850, .t851, .t856, .t858, .t859, .t860, .t881, .t889, .t902, .t912, .t923, .t937, .t959, .t979, .t982, .t983, .t989, .t994');Array.prototype.forEach.call(currentRecChildren,function(child){child.dispatchEvent(event)});var displayChangedBlock=currentRec.querySelector('[data-display-changed="true"]');if(displayChangedBlock)displayChangedBlock.dispatchEvent(event)});var galaxyEffectBlocks=document.querySelectorAll('.t826');Array.prototype.forEach.call(galaxyEffectBlocks,function(galaxyEffectBlock){galaxyEffectBlock.dispatchEvent(event)});t395_startUpdateLazyLoad(targetTab);if(window.lazy==='y'||tildaLazyMode==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})});if(tabs.length){t395_alltabs_updateContent(recid);t395_updateContentBySelect(recid);var bgColor=rec?rec.style.backgroundColor:'#ffffff';var bgColorTargets=rec.querySelectorAll('.t395__select, .t395__firefoxfix');Array.prototype.forEach.call(bgColorTargets,function(target){target.style.background=bgColor})}}
function t395_alltabs_updateContent(recid){var rec=document.getElementById('rec'+recid);var activeTabs=rec?rec.querySelectorAll('.t395__tab_active'):null;var select=rec?rec.querySelector('.t395__select'):null;var tabs=rec.querySelectorAll('.t395__tab');if(activeTabs.length!==1)return!1;var activeTab=activeTabs[0];var hookBlocks=activeTab.getAttribute('data-tab-rec-ids').split(',');var noActive=[];Array.prototype.forEach.call(tabs,function(tab){if(tab!==activeTab){var noActiveHooks=tab.getAttribute('data-tab-rec-ids').split(',');noActiveHooks.forEach(function(hook){if(noActive.indexOf(hook)===-1&&hookBlocks.indexOf(hook)===-1)noActive.push(hook)})}});if(t395_checkVisibillityEl(activeTab)||t395_checkVisibillityEl(select)){hookBlocks.forEach(function(hook){if(hook){var hookEl=document.getElementById('rec'+hook);var hookElRecordType=hookEl?hookEl.getAttribute('data-record-type'):'';if(hookEl)hookEl.classList.remove('t395__off');if(hookEl)hookEl.style.opacity='';t395_updateTabsByHook(hookElRecordType,hookEl,hook,recid)}})}else{hookBlocks.forEach(function(hook){var hookEl=document.getElementById('rec'+hook);if(hookEl)hookEl.setAttribute('data-animationappear','off');if(hookEl)hookEl.classList.add('t395__off')})}
noActive.forEach(function(noActiveID){if(!noActiveID)return;var hookEl=document.getElementById('rec'+noActiveID);var hookElRecordType=hookEl?hookEl.getAttribute('data-record-type'):'';if(hookEl)hookEl.setAttribute('data-connect-with-tab','yes');if(hookEl)hookEl.setAttribute('data-animationappear','off');if(hookEl)hookEl.classList.add('t395__off');t395_updateTabsByHook(hookElRecordType,hookEl,noActiveID,recid)});var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(scrollHeight-window.innerHeight<window.pageYOffset){window.scrollTo(0,0)}}
function t395_updateTabsByHook(hookElRecordType,hookEl,currentID,recid){var hookElTab;switch(hookElRecordType){case '395':if(window.t395_alltabs_updateContent&&window.t395_updateSelect&&recid!==currentID){window.t395_alltabs_updateContent(currentID);window.t395_updateSelect(currentID);hookElTab=hookEl?hookEl.querySelector('.t395__tab'):null;if(hookElTab)hookElTab.click()}
break;case '397':if(recid!==currentID){t397_alltabs_updateContent(currentID);t397_updateSelect(currentID);hookElTab=hookEl?hookEl.querySelector('.t397__tab'):null;if(hookElTab)hookElTab.click()}
break}}
function t395_checkVisibillityEl(el){return!!(el&&(el.offsetWidth||el.offsetHeight||el.getClientRects().length))}
function t395_updateContentBySelect(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var select=rec.querySelector('.t395__select');if(select){select.addEventListener('change',function(){var currentValue=select.value;var tabIndex=rec.querySelector('.t395__tab[data-tab-rec-ids=\''+currentValue+'\']');if(tabIndex)tabIndex.click()})}}
function t395_updateSelect(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var activeTab=rec.querySelector('.t395__tab_active');var currentTabHooks=activeTab?activeTab.getAttribute('data-tab-rec-ids'):'';var select=rec.querySelector('.t395__select');if(select)select.value=currentTabHooks}
function t395_startUpdateLazyLoad(el){var hookBlocks=el?el.getAttribute('data-tab-rec-ids').split(','):[];hookBlocks.forEach(function(hook){var rec=document.getElementById('rec'+hook);if(!rec)return;var videos=rec.querySelectorAll('.t-video-lazyload');if(videos.length){t395_updateVideoLazyLoad(videos)}})}
function t395_updateVideoLazyLoad(videos){setTimeout(function(){Array.prototype.forEach.call(videos,function(video){if(!video.classList.contains('t-video__isload')){var heightAttribute=video.getAttribute('data-videolazy-height');var height=heightAttribute?heightAttribute:'100%';if(height.indexOf('vh')!==-1)height='100%';var videoID=video.getAttribute('data-videolazy-id');videoID=videoID?videoID.trim():'';var blockID=video.getAttribute('data-blocklazy-id');var twoIdAttr=video.getAttribute('data-videolazy-two-id');var videoTwoID=twoIdAttr?'_'+twoIdAttr+'_':'';if(video.getAttribute('data-videolazy-type')==='youtube'){var oldIframe=video.querySelector('iframe');if(oldIframe&&oldIframe.parentNode)oldIframe.parentNode.removeChild(oldIframe);var iframe=document.createElement('iframe');iframe.id='youtubeiframe'+videoTwoID+blockID;iframe.width='100%';iframe.height=height;iframe.src='https://www.youtube.com/embed/'+videoID+'?rel=0&fmt=18&html5=1&showinfo=0';iframe.frameBorder='0';iframe.setAttribute('allowfullscreen','');video.insertAdjacentElement('beforeend',iframe)}}
video.classList.add('t-video__isload')})},2)}
function t395_scrollToTabs(recid){var rec=document.getElementById('rec'+recid);var curUrl=window.location.href;var tabIndexNumber=curUrl.indexOf('#!/tab/');if(tabIndexNumber===-1)return!1;var tabIndexNumberStart=curUrl.indexOf('tab/');var firstOptionSelect=rec?rec.querySelector('.t395__wrapper_mobile .t395__select option'):null;if(firstOptionSelect)firstOptionSelect.selected=!1;var tabRec=curUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length);if(tabRec!==recid)return!1;var tabBlock=rec?rec.querySelector('.t395'):null;var tabNumber=parseInt(curUrl.slice(tabIndexNumberStart+4+recid.length+1),10);var tabs=rec.querySelectorAll('.t395__tab');Array.prototype.forEach.call(tabs,function(tab,i){if(i===tabNumber-1){tab.click();tab.classList.add('t395__tab_active')}else{tab.classList.remove('t395__tab_active')}});var tabsMob=rec.querySelectorAll('.t395__wrapper_mobile .t395__select option');var activeTabMob=tabsMob.length?tabsMob[tabNumber-1]:null;if(activeTabMob)activeTabMob.selected=!0;var targetOffset=tabBlock.getBoundingClientRect().top+window.pageYOffset;var target=window.innerWidth>960?targetOffset-200:targetOffset-100;if(target<0)target=0;t395_scrollToEl(target)}
function t395_scrollToEl(elTopPos){if(elTopPos===window.pageYOffset)return!1;var duration=300;var difference=window.pageYOffset;var cashedDiff=window.pageYOffset;var step=10*(elTopPos||window.pageYOffset)/duration;var timer=setInterval(function(){if(cashedDiff>elTopPos){difference-=step}else{difference+=step}
window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(cashedDiff>elTopPos&&window.pageYOffset<=elTopPos||cashedDiff<=elTopPos&&window.pageYOffset>=elTopPos){document.body.removeAttribute('data-scrollable');clearInterval(timer)}},10);var timer2=setTimeout(function(){clearInterval(timer);document.body.removeAttribute('data-scrollable');clearTimeout(timer2)},duration*2)}
function t395_removeUrl(){var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tab/');if(indexToRemove===-1){indexToRemove=curUrl.indexOf('%23!/tab/')}
curUrl=curUrl.substring(0,indexToRemove);if(indexToRemove!==-1){if(typeof history.replaceState!='undefined'){try{window.history.replaceState('','',curUrl)}catch(err){}}}}
function t400_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t400');if(!container)return;var button=rec.querySelector('.t400__submit');var hideBackText=button.getAttribute('data-hide-back-text');var showMoreText=button.textContent;button.addEventListener('click',function(){if(hideBackText&&button.classList.contains('t400__submit_hide-back')){t400_alltabs_updateContent(recId);button.classList.remove('t400__submit_hide-back');if(button.classList.contains('t400__submit-overflowed')){button.innerHTML='<span class="t400__text">'+showMoreText+'</span>'}else{button.innerHTML=showMoreText}
var zeroBlocks=document.querySelectorAll('.t396');for(var i=0;i<zeroBlocks.length;i++){t400__triggerEvent(zeroBlocks[i],'displayChanged')}
return}
var recIds=button.getAttribute('data-hidden-rec-ids').split(',');for(var i=0;i<recIds.length;i++){var recShowBlock=document.getElementById('rec'+recIds[i]);if(recShowBlock){recShowBlock.classList.remove('t400__off');recShowBlock.style.opacity='';var videos=recShowBlock.querySelectorAll('.t-video-lazyload');if(videos.length>0){var video=videos[0];if(video.closest('.t121')||video.closest('.t223')||video.closest('.t230')||video.closest('.t368')){t400_updateVideoLazyLoad(videos)}}
var selectors=recShowBlock.querySelectorAll('.t-feed, .t-store, .t-store__product-snippet, .t117, .t121, .t132, .t223, .t226, .t228, .t229, .t230, .t268, .t279, .t341, .t346, .t347, .t349, .t351, .t353, .t384, .t385, .t386, .t396, .t400, .t404, .t409, .t410, .t412, .t418, .t422, .t425, .t428, .t433, .t456, .t477, .t478, .t480, .t486, .t498, .t504, .t506, .t509, .t511, .t517, .t518, .t519, .t520, .t527, .t531, .t532, .t533, .t538, .t539, .t544, .t545, .t552, .t554, .t570, .t577, .t592, .t598, .t599, .t601, .t604, .t605, .t609, .t615, .t616, .t650, .t659, .t670, .t675, .t686, .t688, .t694, .t698, .t700, .t726, .t728, .t730, .t734, .t738, .t740, .t744, .t754, .t760, .t762, .t764, .t774, .t776, .t778, .t780, .t786, .t798, .t799, .t801, .t813, .t814, .t822, .t826, .t827, .t829, .t842, .t843, .t849, .t850, .t851, .t856, .t858, .t859, .t860, .t881, .t889, .t899, .t902, .t905, .t912, .t923, .t937, .t958, .t959, .t979, .t982, .t983, .t989, .t994, .t1000, .t1003');for(var j=0;j<selectors.length;j++){t400__triggerEvent(selectors[j],'displayChanged')}}}
if(hideBackText){button.classList.add('t400__submit_hide-back');if(button.classList.contains('t400__submit-overflowed')){button.innerHTML='<span class="t400__text">'+hideBackText+'</span>'}else{button.innerHTML=hideBackText}}else{rec.classList.add('t400__off');rec.style.display='none'}
if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}});t400_alltabs_updateContent(recId);t400_checkSize(recId);if(typeof jQuery!=='undefined'){$(container).bind('displayChanged',function(){t400_checkSize(recId)})}else{container.addEventListener('displayChanged',function(){t400_checkSize(recId)})}}
function t400_alltabs_updateContent(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var button=rec.querySelector('.t400__submit');if(!button)return;var recIds=button.getAttribute('data-hidden-rec-ids').split(',');for(var i=0;i<recIds.length;i++){var recHideBlock=document.getElementById('rec'+recIds[i]);if(!recHideBlock)return;recHideBlock.setAttribute('data-animationappear','off');recHideBlock.setAttribute('data-connect-with-tab','yes');recHideBlock.classList.add('t400__off')}}
function t400_checkSize(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var button=rec.querySelector('.t400__submit');if(!button)return;var buttonStyle=getComputedStyle(button,null);var buttonPaddingTop=parseInt(buttonStyle.paddingTop)||0;var buttonPaddingBottom=parseInt(buttonStyle.paddingBottom)||0;var buttonHeight=button.clientHeight-(buttonPaddingTop+buttonPaddingBottom);var buttonScrollHeight=button.scrollHeight;if(buttonHeight<buttonScrollHeight){var buttonText=button.textContent;button.classList.add('t400__submit-overflowed');button.innerHTML='<span class="t400__text">'+buttonText+'</span>'}}
function t400_updateVideoLazyLoad(videos){setTimeout(function(){for(var i=0;i<videos.length;i++){var video=videos[i];var videoHeight=video.getAttribute('data-videolazy-height')||'100%';if(videoHeight.indexOf('vh')!==-1){videoHeight='100%'}
var videoId=video.getAttribute('data-videolazy-id').trim();var blockId=video.getAttribute('data-blocklazy-id')||'';var videoTwoId=video.getAttribute('data-videolazy-two-id')||'';if(videoTwoId)videoTwoId='_'+videoTwoId+'_';if(video.getAttribute('data-videolazy-type')==='youtube'){var iframes=video.querySelectorAll('iframe');for(var j=0;j<iframes.length;j++){var oldFrame=iframes[j];if(oldFrame&&oldFrame.parentNode)oldFrame.parentNode.removeChild(oldFrame)}
var iframe=document.createElement('iframe');iframe.id='youtubeiframe'+videoTwoId+blockId;iframe.width='100%';iframe.height=videoHeight;iframe.src='//www.youtube.com/embed/'+videoId+'?rel=0&fmt=18&html5=1&showinfo=0';iframe.setAttribute('frameborder','0');iframe.setAttribute('allowfullscreen','');video.insertBefore(iframe,video.firstChild)}}})}
function t400__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}
function t509_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t509');if(!container)return;var images=rec.querySelectorAll('.t509__blockimg');for(var i=0;i<images.length;i++){var image=images[i];var imageWidth=image.getAttribute('data-image-width');var imageHeight=image.getAttribute('data-image-height');if(imageHeight.indexOf('vh')===-1){imageHeight=parseInt(imageHeight,10)}else{imageHeight=parseInt(imageHeight,10)/100*window.innerHeight}
var imageRatio=imageHeight/imageWidth;var imagePadding=imageRatio*100;image.style.paddingBottom=imagePadding+'%'}
if(window.innerWidth>960){var desktopImage=rec.querySelector('.t509__desktopimg');if(desktopImage){var height=desktopImage.clientHeight;var textWrappers=rec.querySelectorAll('.t509__textwrapper');for(var i=0;i<textWrappers.length;i++){textWrappers[i].style.height=height+'px'}}}}
function t527_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t527');if(!container)return;var images=rec.querySelectorAll('.t527__bgimg');if(!images[0])return;var imageWidth=images[0].getAttribute('data-image-width');var imageHeight=images[0].getAttribute('data-image-height');var imageRatio=imageHeight/imageWidth;var imagePadding=imageRatio*100;for(var i=0;i<images.length;i++){images[i].style.paddingBottom=imagePadding+'%'}}
function t585_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var accordion=rec.querySelectorAll('.t585__accordion')[0];var headers=rec.querySelectorAll('.t585__header');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');var accordionScroll;if(accordion){accordionScroll=accordion.getAttribute('data-scroll-to-expanded');accordion=accordion.getAttribute('data-accordion')}else{accordion='false';accordionScroll='false'}
for(var i=0;i<headers.length;i++){headers[i].addEventListener('click',function(){var element=this;var container=element.nextElementSibling;var activeHeight=0;var isAccordionDown=!1;if(element.classList.contains('t585__opened')){element.classList.remove('t585__opened');t585_accordionHide(container)}else{if(accordionScroll==='true'&&accordion==='true'){activeHeight=t585__getOldAction(rec);isAccordionDown=t585__getAccordionPosition(headers,element)}
if(accordion==='true')t585_accordionAllHide(headers);element.classList.add('t585__opened');container.style.display='block';var height=container.scrollHeight;container.style.maxHeight='0px';setTimeout(function(){container.style.maxHeight=height+'px';if(accordionScroll==='true'){t585__calcHeight(element,container,activeHeight,isAccordionDown)}},0)}
if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}}
function t585_accordionAllHide(headers){for(var i=0;i<headers.length;i++){var elementHide=headers[i];elementHide.classList.remove('t585__opened');t585_accordionHide(elementHide.nextElementSibling)}}
function t585_accordionHide(container){if(!container.style.maxHeight)container.style.maxHeight=container.scrollHeight+'px';setTimeout(function(){container.style.maxHeight='0px'},0)}
function t585__getOldAction(rec){var activeHeader=rec.querySelector('.t585__opened');var activeHeight=0;if(activeHeader)var activeContainer=activeHeader.nextElementSibling;if(activeContainer)activeHeight=activeContainer.offsetHeight;return activeHeight}
function t585__getAccordionPosition(headers,element){var oldIndex;var newIndex;for(var i=0;i<headers.length;i++){var header=headers[i];if(header.classList.contains('t585__opened'))oldIndex=i;if(header===element)newIndex=i}
return oldIndex<newIndex?!0:!1}
function t585__calcHeight(element,container,activeHeight,isAccordionDown){var windowHeight=window.innerHeight;var windowScroll=window.scrollY;var containerHeight=container.scrollHeight;var accordionHeight=containerHeight+element.offsetHeight;var elementTopOffset=element.getBoundingClientRect().top+windowScroll;var target=isAccordionDown?elementTopOffset-activeHeight:elementTopOffset;if(target<windowScroll||accordionHeight>windowHeight){t585__scroll(target)}}
function t585__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t585__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t585__animateScroll(){currentTime+=increment;window.scrollTo(0,t585__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t585__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t585__animateScroll()}
function t650_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t650');if(!container)return;var rows=rec.querySelectorAll('.t650__row');if(window.innerWidth>=960){for(var i=0;i<rows.length;i++){var row=rows[i];var maxHeight=0;var cols=row.querySelectorAll('.t650__inner-col');for(var j=0;j<cols.length;j++){var col=cols[j];var colText=col.querySelector('.t650__text');var colBtn=col.querySelector('.t650__btn-container');var colHeight=colText.offsetHeight+(colBtn?colBtn.offsetHeight:0);if(colHeight>maxHeight)maxHeight=colHeight}
for(var j=0;j<cols.length;j++){cols[j].style.height=maxHeight+'px'}}}else{var cols=rec.querySelectorAll('.t650__inner-col');for(var i=0;i<cols.length;i++){cols[i].style.height='auto'}}}
function t668_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t668');if(!container)return;var accordion=rec.querySelectorAll('.t668__accordion')[0];var headers=rec.querySelectorAll('.t668__header');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');var contentStyle=getComputedStyle(rec.querySelector('.t668__content'),null);var oldStyle={paddingTop:contentStyle.paddingTop,paddingBottom:contentStyle.paddingBottom};var zeroBlocks=document.querySelectorAll('.t396');var event=document.createEvent('Event');if(accordion){accordion=accordion.getAttribute('data-accordion')}else{accordion='false'}
for(var i=0;i<headers.length;i++){headers[i].addEventListener('click',function(){var element=this;var container=element.nextElementSibling;Array.prototype.forEach.call(zeroBlocks,function(zero){event.initEvent('displayChanged',!0,!0);zero.dispatchEvent(event)});if(element.classList.contains('t668__opened')){element.classList.remove('t668__opened');t668_accordionHide(container)}else{if(accordion==='true'){t668_accordionAllHide(headers)}
element.classList.add('t668__opened');container.style.display='block';var height=container.scrollHeight;container.style.maxHeight='0px';setTimeout(function(){container.style.maxHeight=height+'px';container.setAttribute('style',t668_addStyle(container)+' padding-top: '+oldStyle.paddingTop+'; padding-bottom: '+oldStyle.paddingBottom+';')},0)}
if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}}
function t668_accordionAllHide(headers){for(var i=0;i<headers.length;i++){var elementHide=headers[i];elementHide.classList.remove('t668__opened');t668_accordionHide(elementHide.nextElementSibling)}}
function t668_accordionHide(container){if(!container.style.maxHeight)container.style.maxHeight=container.scrollHeight+'px';setTimeout(function(){container.style.maxHeight=0;container.setAttribute('style',t668_addStyle(container)+' padding-top: 0px !important; padding-bottom: 0px !important;')},0)}
function t668_addStyle(container){var attrStyle=container.getAttribute('style');var arrStyle=attrStyle.split(';');var newArr=[];for(var i=0;i<arrStyle.length;i++){var style=arrStyle[i];if(style.indexOf('padding-top')===-1&&style.indexOf('padding-bottom')===-1){newArr.push(style)}}
return newArr.join(';')}
function t678_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t678__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t678__fadeOut(tildaLabel,50)}},300)}else{t678__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t678__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t678__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t678__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t678__easeInOutCubic(currentTime,change){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t678__animateScroll(){currentTime+=increment;window.scrollTo(0,t678__easeInOutCubic(currentTime,change));if(currentTime<duration){setTimeout(t678__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t678__animateScroll()}
function t702_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var submitHref=rec.querySelector('.t-submit[href*="#"]');if(popupTooltipHook){var recBlocks=document.querySelectorAll('.r');for(var i=0;i<recBlocks.length;i++){recBlocks[i].addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t702_showPopup(recId);t702_resizePopup(recId);t702__lazyLoad();if(analitics){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}})}}
popup.addEventListener('scroll',t_throttle(function(){t702__lazyLoad()}));popup.addEventListener('click',function(event){var windowWithoutScrollBar=window.innerWidth-17;if(event.clientX>windowWithoutScrollBar)return;if(event.target===this)t702_closePopup()});popupCloseBtn.addEventListener('click',t702_closePopup);if(submitHref){submitHref.addEventListener('click',function(){if(documentBody.classList.contains('t-body_scroll-locked')){documentBody.classList.remove('t-body_scroll-locked')}})}
for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){documentBody.classList.add('t-body_popupshowed')},300)}}})}}
function t702_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t702_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t702_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var range=rec.querySelector('.t-range');var documentBody=document.body;popup.style.display='block';if(range)t702__triggerEvent(range,'popupOpened');setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},50);documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){setTimeout(function(){t702_lockScroll()},500)}
document.addEventListener('keydown',t702_escClosePopup);t702__lazyLoad()}
function t702_escClosePopup(event){if(event.key==='Escape')t702_closePopup()}
function t702_closePopup(){var popupAll=document.querySelectorAll('.t-popup');document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t702__body_popupshowed');for(var i=0;i<popupAll.length;i++){popupAll[i].classList.remove('t-popup_show')}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){t702_unlockScroll()}
setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',t702_escClosePopup)}
function t702_resizePopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var popupContainer=rec.querySelector('.t-popup__container');if(!popupContainer)return;var popupStyle=getComputedStyle(popupContainer,null);var popupPaddingTop=parseInt(popupStyle.paddingTop)||0;var popupPaddingBottom=parseInt(popupStyle.paddingBottom)||0;var popupHeight=popupContainer.clientHeight-(popupPaddingTop+popupPaddingBottom);if(popupHeight>(window.innerHeight-120)){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t702_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t702__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t702__fadeOut(tildaLabel)}},300)}else{t702__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t702__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t702__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t702__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t702__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t702__animateScroll(){currentTime+=increment;window.scrollTo(0,t702__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t702__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t702__animateScroll()}
function t702__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t702__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}
function t817_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var currentMode=document.querySelector('.t-records').getAttribute('data-tilda-mode');var tabs=rec.querySelectorAll('.t817__tab');var select=rec.querySelector('.t817__select');var content=rec.querySelectorAll('.t817__content');if(!tabs.length)return;if(!content.length)return;if(currentMode!=='edit'&&currentMode!=='preview'){t817_scrollToTabs(recid);window.onload=function(){t817_scrollToTabs(recid)}}
t817_showTabByUrl(recid,tabs,content,select);t817_showTab(recid,tabs,content,currentMode);t817_showTabMobile(recid,select,content,currentMode)}
function t817_showTab(recid,tabs,content,currentMode){Array.prototype.forEach.call(tabs,function(tabItem){tabItem.addEventListener('click',function(event){var tabNumber=this.getAttribute('data-tab-number');Array.prototype.forEach.call(tabs,function(tabItem){tabItem.classList.remove('t817__tab_active')});Array.prototype.forEach.call(content,function(contentItem){contentItem.classList.remove('t817__content_active');if(parseInt(contentItem.getAttribute('data-tab-content-number'),10)===parseInt(tabNumber,10)){contentItem.classList.add('t817__content_active')}});tabItem.classList.add('t817__tab_active');t817_removeUrl();if(currentMode!=='edit'&&currentMode!=='preview'){if(typeof history.replaceState==='function'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumber)}}
if(!currentMode){if(window.lazy==='y'||document.querySelector('#allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
event.preventDefault()})})}
function t817_showTabMobile(recid,select,content,currentMode){select.addEventListener('change',function(event){var tabNumberMobile=this.value;Array.prototype.forEach.call(content,function(contentItem){contentItem.classList.remove('t817__content_active');if(parseInt(contentItem.getAttribute('data-tab-content-number'),10)===parseInt(tabNumberMobile,10)){contentItem.classList.add('t817__content_active')}});t817_removeUrl();if(currentMode!=='edit'&&currentMode!=='preview'){if(typeof history.replaceState==='function'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumberMobile)}}
if(!currentMode){if(window.lazy==='y'||document.querySelector('#allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
event.preventDefault()})}
function t817_showTabByUrl(recid,tabs,content,select){var currentUrl=window.location.href;var tabIndexNumber=currentUrl.indexOf(recid+'-');var tabIndex=currentUrl.substring(tabIndexNumber+recid.length+1);if(tabIndexNumber!==-1){Array.prototype.forEach.call(tabs,function(tabItem){if(parseInt(tabItem.getAttribute('data-tab-number'),10)===parseInt(tabIndex,10)){tabItem.classList.add('t817__tab_active')}});Array.prototype.forEach.call(content,function(contentItem){if(parseInt(contentItem.getAttribute('data-tab-content-number'),10)===parseInt(tabIndex,10)){contentItem.classList.add('t817__content_active')}});select.value=tabIndex}else{tabs[0].classList.add('t817__tab_active');content[0].classList.add('t817__content_active')}}
function t817_scrollToTabs(recid){var currentUrl=window.location.href;var tabIndexNumber=currentUrl.indexOf('#!/tab/');var tabIndexNumberStart=currentUrl.indexOf('tab/');if(parseInt(tabIndexNumber,10)!==-1){var tabRecord=currentUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length);if(parseInt(tabRecord,10)===parseInt(recid,10)){var tabBlock=document.querySelector('#rec'+tabRecord).querySelector('.t817');var targetOffset=tabBlock.getBoundingClientRect().top+window.pageYOffset;if(window.innerWidth>960){var target=targetOffset-200}else{var target=targetOffset-100}
t817_scrollToEl(target,300)}}}
function t817_removeUrl(){var currentUrl=window.location.href;var indexToRemove=currentUrl.indexOf('#!/tab/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=currentUrl.indexOf('%23!/tab/')}
currentUrl=currentUrl.substring(0,indexToRemove);if(parseInt(indexToRemove,10)!==-1){if(typeof history.replaceState==='function'){window.history.replaceState('','',currentUrl)}}}
function t817_scrollToEl(elTopPos,duration){if(elTopPos===window.pageYOffset)return!1;var difference=window.pageYOffset;var cashedDiff=window.pageYOffset;var step=(10*(elTopPos||window.pageYOffset))/duration;var timer=setInterval(function(){if(cashedDiff>elTopPos){difference-=step}else{difference+=step}
window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(cashedDiff>elTopPos&&window.pageYOffset<=elTopPos){document.body.removeAttribute('data-scrollable');clearInterval(timer)}else if(cashedDiff<=elTopPos&&window.pageYOffset>=elTopPos){document.body.removeAttribute('data-scrollable');clearInterval(timer)}},10);var timer2=setTimeout(function(){clearInterval(timer);document.body.removeAttribute('data-scrollable');clearTimeout(timer2)},duration*2)}
function t858_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t858');if(!container)return;t858_unifyHeights(recId);window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.noAdaptive===!0&&window.isMobile)return;t858_unifyHeights(recId)}));window.addEventListener('load',function(){t858_unifyHeights(recId)});if(typeof jQuery!=='undefined'){$(container).on('displayChanged',function(){t858_unifyHeights(recId)})}else{container.addEventListener('displayChanged',function(){t858_unifyHeights(recId)})}
if(container.classList.contains('t858__previewmode')){setInterval(function(){t858_unifyHeights(recId)},5000)}}
function t858_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t858');if(!container)return;if(window.innerWidth>=960){var rows=container.querySelectorAll('.t858__row');for(var i=0;i<rows.length;i++){var row=rows[i];var maxHeight=0;var cols=row.querySelectorAll('.t858__inner-col');for(var j=0;j<cols.length;j++){var col=cols[j];var colWrap=col.querySelector('.t858__wrap');var colHeight=colWrap.offsetHeight;if(colHeight>maxHeight)maxHeight=colHeight}
for(var j=0;j<cols.length;j++){cols[j].style.height=maxHeight+'px'}}}else{var cols=rec.querySelectorAll('.t858__inner-col');for(var i=0;i<cols.length;i++){cols[i].style.height='auto'}}}
function t890_init(recId,offset){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t890');if(!container)return;var button=rec.querySelector('.t890__arrow');var windowOffset='';if(offset){windowOffset=offset}else{windowOffset=window.innerHeight}
rec.setAttribute('data-animationappear','off');rec.style.opacity=1;window.addEventListener('scroll',t_throttle(function(){if(window.pageYOffset>windowOffset){container.style.display='block'}else{t890__fadeOut(container)}},200));button.addEventListener('click',t890__scrollToTop)}
function t890__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},20)}
function t890__scrollToTop(){if(window.isIE){window.scrollTo(0,0)}else{window.scrollTo({left:0,top:0,behavior:'smooth'})}}
function t923_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t923');if(!container)return;t923_unifyHeights(recId);window.addEventListener('resize',t_throttle(function(){t923_unifyHeights(recId)}));if(typeof jQuery!=='undefined'){$(container).on('displayChanged',function(){t923_unifyHeights(recId)})}else{container.addEventListener('displayChanged',function(){t923_unifyHeights(recId)})}
window.addEventListener('load',function(){t923_unifyHeights(recId)})}
function t923_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t923');if(!container)return;var cols=rec.querySelectorAll('.t923__content');var maxHeight=0;for(var i=0;i<cols.length;i++){cols[i].style.height=''}
for(var i=0;i<cols.length;i++){var col=cols[i];var colText=col.querySelector('.t923__textwrapper');var colBtn=col.querySelectorAll('.t923__btn-wrapper, .t923__btntext-wrapper')[0];var colHeight=colText.offsetHeight+(colBtn?colBtn.offsetHeight:0);if(colHeight>maxHeight)maxHeight=colHeight}
for(var i=0;i<cols.length;i++){cols[i].style.height=maxHeight+'px'}
t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recId)})}
function t992_init(recid){t992_highlight();t992_checkAnchorLinks(recid)}
function t992_highlight(){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t992__list-item a[href=\''+url+'\'], '+'.t992__list-item a[href=\''+url+'/\'], '+'.t992__list-item a[href=\''+pathname+'\'], '+'.t992__list-item a[href=\'/'+pathname+'\'], '+'.t992__list-item a[href=\''+pathname+'/\'], '+'.t992__list-item a[href=\'/'+pathname+'/\'], '+'.t992__list-item a[href=\'/'+hash+'/\']');Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t992_checkAnchorLinks(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<980)return;var navLinks=rec.querySelectorAll('.t992__list-item a[href*=\'#\']');navLinks=Array.prototype.filter.call(navLinks,function(navLink){return!navLink.classList.contains('tooltipstered')});if(navLinks.length){t992_catchScroll(navLinks)}}
function t992_catchScroll(navLinks){var clickedSectionID=null;var sections=[];var sectionToNavigationLinkID={};var interval=100;var lastCall;var timeoutID;navLinks=navLinks.reverse();navLinks.forEach(function(link){var currentSection=t992_getSectionByHref(link);if(currentSection&&currentSection.id){sections.push(currentSection);sectionToNavigationLinkID[currentSection.id]=link}});t992_updateSectionsOffsets(sections);sections.sort(function(a,b){var firstTopOffset=parseInt(a.getAttribute('data-offset-top'),10)||0;var secondTopOffset=parseInt(b.getAttribute('data-offset-top'),10)||0;return secondTopOffset-firstTopOffset});window.addEventListener('resize',t_throttle(function(){t992_updateSectionsOffsets(sections)},200));$('.t992').bind('displayChanged',function(){t992_updateSectionsOffsets(sections)});var menuEls=document.querySelectorAll('.t992');Array.prototype.forEach.call(menuEls,function(menu){menu.addEventListener('displayChanged',function(){t992_updateSectionsOffsets(sections)})});setInterval(function(){t992_updateSectionsOffsets(sections)},5000);t992_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID);navLinks.forEach(function(navLink,i){navLink.addEventListener('click',function(){var clickedSection=t992_getSectionByHref(navLink);if(!navLink.classList.contains('tooltipstered')&&clickedSection&&clickedSection.id){navLinks.forEach(function(link,index){if(index===i){link.classList.add('t-active')}else{link.classList.remove('t-active')}});clickedSectionID=clickedSection.id}})});window.addEventListener('scroll',function(){var dateNow=new Date().getTime();if(lastCall&&dateNow<lastCall+interval){clearTimeout(timeoutID);timeoutID=setTimeout(function(){lastCall=dateNow;clickedSectionID=t992_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)},interval-(dateNow-lastCall))}else{lastCall=dateNow;clickedSectionID=t992_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)}})}
function t992_updateSectionsOffsets(sections){sections.forEach(function(section){var sectionTopPos=section.getBoundingClientRect().top+window.pageYOffset;section.setAttribute('data-offset-top',sectionTopPos)})}
function t992_getSectionByHref(curlink){if(!curlink)return;var href=curlink.getAttribute('href');var curLinkValue=href?href.replace(/\s+/g,''):'';if(curLinkValue.indexOf('/')===0)curLinkValue=curLinkValue.slice(1);if(href&&curlink.matches('[href*="#rec"]')){curLinkValue=curLinkValue.replace(/.*#/,'');return document.getElementById(curLinkValue)}else{var selector=href?href.trim():'';var slashIndex=selector.indexOf('#')!==-1?selector.indexOf('#'):!1;if(typeof slashIndex==='number'){selector=selector.slice(slashIndex+1)}else{slashIndex=selector.indexOf('/')!==-1?selector.indexOf('/'):!1;if(typeof slashIndex==='number')selector=selector.slice(slashIndex+1)}
var fullSelector='.r[data-record-type="215"] a[name="'+selector+'"]';return document.querySelector(fullSelector)?document.querySelector(fullSelector).closest('.r'):null}}
function t992_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID){var scrollPosition=window.pageYOffset;var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var returnValue=clickedSectionID;var lastSection=sections.length?sections[sections.length-1]:null;var lastSectionTopPos=lastSection?lastSection.getAttribute('data-offset-top'):'0';lastSectionTopPos=parseInt(lastSectionTopPos,10)||0;if(sections.length&&clickedSectionID===null&&lastSectionTopPos>(scrollPosition+300)){navLinks.forEach(function(link){link.classList.remove('t-active')});return null}
for(var i=0;i<sections.length;i++){var sectionTopPos=sections[i].getAttribute('data-offset-top');var navLink=sections[i].id?sectionToNavigationLinkID[sections[i].id]:null;if(scrollPosition+300>=sectionTopPos||i===0&&scrollPosition>=scrollHeight-window.innerHeight){if(clickedSectionID===null&&navLink&&!navLink.classList.contains('t-active')){navLinks.forEach(function(link){link.classList.remove('t-active')});if(navLink)navLink.classList.add('t-active');returnValue=null}else if(clickedSectionID!==null&&sections[i].id&&clickedSectionID===sections[i].id){returnValue=null}
break}}
return returnValue}
function t1003_init(recId,angle){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t1003');if(!container)return;t1003_calc(rec,recId,angle);window.addEventListener('resize',t_throttle(function(){t1003_calc(rec,recId,angle)},300));window.addEventListener('load',function(){t1003_calc(rec,recId,angle)});if(typeof jQuery!=='undefined'){$(container).bind('displayChanged',function(){t1003_calc(rec,recId,angle)})}else{container.addEventListener('displayChanged',function(){t1003_calc(rec,recId,angle)})}}
function t1003_calc(rec,recId,angle){var wrapper=rec.querySelector('.t1003__wrapper');var contentWrapper=rec.querySelector('.t1003__content-wrapper');var content=rec.querySelector('.t1003__content');var items=content.querySelectorAll('.t1003__item');var img=items[0].querySelector('.t1003__bgimg');var index=0;if(img){for(var i=0;i<items.length;i++){if(items[i].querySelector('.t1003__bgimg').classList.contains('loaded')){index=i;break}}}
var itemWidth=items[index].offsetWidth;var windowWidth=window.innerWidth;var itemsToDisplay=parseInt(windowWidth/itemWidth)+3;var direction='';t1003_calcRotatedWidth(rec,angle);if(wrapper.getAttribute('data-marquee-direction')==='opposite')direction='right';for(var i=1;i<items.length;i++){t1003__remove(items[i])}
for(var i=0;i<itemsToDisplay;i++){if(direction==='right'){content.insertBefore(items[index].cloneNode(!0),items[0])}else{content.insertBefore(items[index].cloneNode(!0),items[0].nextSibling)}}
t1003_anim(rec,itemWidth,recId,direction);content.style.animationName='t1003__anim-scrolling_'+recId;contentWrapper.style.opacity='1'}
function t1003_calcRotatedWidth(rec,angle){var outer=rec.querySelector('.t1003__outer');var wrapper=rec.querySelector('.t1003__wrapper');wrapper.removeAttribute('style');angle=parseFloat(angle.replace('deg',''),10);var windowWidth=window.innerWidth;var angleRad=(angle*Math.PI)/180;var sin=Math.sin(angleRad);var paddingCoeff=Math.abs(Math.tan(angleRad)/2);var padding=windowWidth*paddingCoeff;var rotatedHeight=Math.abs(sin*windowWidth);wrapper.style.width='calc(100vw + '+padding+'px)';wrapper.style.padding='0 '+padding+'px';var wrapperStyle=getComputedStyle(wrapper,null);var wrapperPaddingTop=parseInt(wrapperStyle.paddingTop)||0;var wrapperPaddingBottom=parseInt(wrapperStyle.paddingBottom)||0;var wrapperPaddingLeft=parseInt(wrapperStyle.paddingLeft)||0;var wrapperPaddingRight=parseInt(wrapperStyle.paddingRight)||0;var wrapperWidth=wrapper.clientWidth-(wrapperPaddingLeft+wrapperPaddingRight);var wrapperHeight=wrapper.clientHeight-(wrapperPaddingTop+wrapperPaddingBottom);var operator=(sin<0)?'':'-';outer.style.height=(rotatedHeight+wrapperHeight)+'px';if(window.isIE){wrapper.style.width='';wrapper.style.marginLeft='-'+wrapperWidth/2+'px';wrapper.style.marginTop=operator+wrapperHeight/2+'px'}}
function t1003_anim(rec,itemWidth,id,direction){var animationName='t1003__anim-scrolling_'+id;var speedAttr=rec.querySelector('.t1003__wrapper').getAttribute('data-marquee-speed');var start;var end;var speed;var seconds;var styleAnimation=rec.querySelector('#'+animationName);if(styleAnimation)t1003__remove(styleAnimation);if(!speedAttr)return;seconds=parseFloat(speedAttr.replace('s',''));speed=(itemWidth/100)*seconds;rec.querySelector('.t1003__content').style.animationDuration=speed+'s';if(direction==='right'){start=itemWidth*-1;end=0}else{start=0;end=itemWidth*-1}
var style=document.createElement('style');style.id=animationName;style.innerHTML='@keyframes '+animationName+'{'+'0% {'+'transform: translateX('+start+'px);'+'-webkit-transform: translateX('+start+'px);'+'}'+'100% {'+'transform: translateX('+end+'px);'+'-webkit-transform: translateX('+end+'px);'+'}'+'}';rec.appendChild(style)}
function t1003__remove(el){if(el&&el.parentNode){el.parentNode.removeChild(el)}}