const responses = [
	'It is <br> certain.',
	'It is <br> decidedly so.',
	'Without <br>a doubt.',
	'Yes - definitely.',
	'You may<br> rely on it.',
	'As I see it,<br> yes.',
	'Most likely.',
	'Outlook good.',
	'Yes.',
	'Signs point <br> to yes.',
	'Reply hazy, <br>try again.',
	'Ask again<br> later.',
	'Better not <br>tell you now.',
	'Cannot <br>predict now.',
	'Concentrate <br>and ask again.',
	'Don\'t count<br> on it.',
	'My reply is no.',
	'My sources <br> say no.',
	'Outlook not so good.',
	'Very doubtful.'
];